### ISSUE TITLE
建议添加自定义扫描路径功能

### ISSUE THREAD

**Issue by huahaiYa** [Tsojan/TsojanScan#14]
建议添加自定义扫描路径功能

**Comment by TheCryingGame** [comment]
自定义路径扫描相同的功能dirsearch已经实现，如果需要自定义扫描路径，插件会加载路径文本，会重新计算数据流，线程会变得非常大，Burp会卡顿，这个我门内部已经测试过了，所以放弃掉这个模块，插件的本意是用最小的线程和数据包请求去探测漏洞，这已经违背了我们的初衷:(

**Comment by TheCryingGame** [comment]
> 自定义路径扫描相同的功能dirsearch已经实现，如果需要自定义扫描路径，插件会加载路径文本，会重新计算数据流，线程会变得非常大，Burp会卡顿，这个我门内部已经测试过了，所以放弃掉这个模块，插件的本意是用最小的线程和数据包请求去探测漏洞，这已经违背了我们的初衷:(

**Comment by TheCryingGame** [comment]
> 建议添加自定义扫描路径功能

自定义路径扫描相同的功能dirsearch已经实现，如果需要自定义扫描路径，插件会加载路径文本，会重新计算数据流，线程会变得非常大，Burp会卡顿，这个我门内部已经测试过了，所以放弃掉这个模块，插件的本意是用最小的线程和数据包请求去探测漏洞，这已经违背了我们的初衷:(

**Comment by chenxing0903** [comment]
为什么无法使用被动扫描

**Comment by chenxing0903** [comment]
大佬，为什么无法使用被动扫描只能主动扫 ？
