### ISSUE TITLE
报错：dnslog初始化失败

### ISSUE THREAD

**Issue by why-git-why** [Tsojan/TsojanScan#2]
![111](https://user-images.githubusercontent.com/80434632/218917976-5dc08c10-d65f-4f18-8a9b-679c1fa74af3.png)

师傅域名初始化失败，能不能自定义配配置dnslog地址

**Comment by why-git-why** [comment]
解决了，多加载几次就行了

**Comment by TheCryingGame** [comment]
已更新，请使用新版本
