### ISSUE TITLE
为什么有时候会失效？

### ISSUE THREAD

**Issue by shannaburns** [Tsojan/TsojanScan#55]
同一个站在我旁边的师傅能扫出来洞，我扫不出来，被动扫描也开着，然后我重新卸载插件再安装就可以了。请问我怎么确定这个插件是再工作

**Comment by TheCryingGame** [comment]
提示加载成功即能正常工作，需要开启burpsuite功能
<img width="949" alt="image" src="https://github.com/user-attachments/assets/d29aba7f-780f-49c8-b268-cbb67efbb17a">
