### ISSUE TITLE
fastjson 扫描出错java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1 

### ISSUE THREAD

**Issue by ruiwen123** [Tsojan/TsojanScan#9]
fastjson 扫描出错java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
fastjson 扫描出错java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
fastjson 扫描出错java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
fastjson 扫描出错java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
fastjson 扫描出错java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
fastjson 扫描出错java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
fastjson 扫描出错java.lang.IllegalArgumentException: URLDecoder: Illegal hex characters in escape (%) pattern - Error at index 0 in: ")�"
fastjson 扫描出错java.lang.IllegalArgumentException: URLDecoder: Illegal hex characters in escape (%) pattern - Error at index 0 in: "�ޭ"
fastjson 扫描出错java.lang.IllegalArgumentException: URLDecoder: Illegal hex characters in escape (%) pattern - Error at index 0 in: ">�"

**Comment by teamtopkarl** [comment]
我也有这样的问题
fastjson 扫描出错java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
fastjson 扫描出错java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
fastjson 扫描出错java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1

**Comment by TheCryingGame** [comment]
这个报错是代码的的问题，后续更新会修复。。

**Comment by TheCryingGame** [comment]
> fastjson 扫描出错java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1 fastjson 扫描出错java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1 fastjson 扫描出错java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1 fastjson 扫描出错java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1 fastjson 扫描出错java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1 fastjson 扫描出错java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1 fastjson 扫描出错java.lang.IllegalArgumentException: URLDecoder: Illegal hex characters in escape (%) pattern - Error at index 0 in: ")�" fastjson 扫描出错java.lang.IllegalArgumentException: URLDecoder: Illegal hex characters in escape (%) pattern - Error at index 0 in: "�ޭ" fastjson 扫描出错java.lang.IllegalArgumentException: URLDecoder: Illegal hex characters in escape (%) pattern - Error at index 0 in: ">�"



> 我也有这样的问题 fastjson 扫描出错java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1 fastjson 扫描出错java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1 fastjson 扫描出错java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1

这个报错是代码的的问题，后续更新会修复。。

**Comment by xiaowunb** [comment]
解决了吗

**Comment by TheCryingGame** [comment]
> 解决了吗

新版已修复
